version: '3'
services:
  web:
    container_name: "web"
    image: "nginx:latest"
    build:
      context: .
      dockerfile: "./docker/web/Dockerfile"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www/html"
      - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

  php:
    container_name: "php"
    build:
      context: .
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - "./src:/var/www/html"

  db:
    container_name: "db"
    image: "mysql:8.0"
    environment:
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=hellotrip_db"
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
    ports:
      - 3000:80
    volumes:
      - ./phpadmin/sessions:/sessions

volumes:
  db-data:
