services:
  web:
    # コンテナ名
    container_name: "web"
    # イメージ名
    image: "nginx:latest"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: "./docker/web/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8080:80"
    # src配下のファイルをコンテナ内の~/var/www/html配下に配置
    volumes:
      - "./src:/var/www/html"

  php:
    # コンテナ名
    container_name: "php"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: "./docker/php/Dockerfile"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./src:/var/www/html"

  db:
    # コンテナ名
    container_name: "db"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: "./docker/db/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=hellotrip_db"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./docker/db/data:/var/lib/mysql"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
    ports:
      - 3000:80
    volumes:
      - ./phpadmin/sessions:/sessionserror_log